name: device_info_plus_harmonyos
description: "HarmonyOS implementation of the device_info_plus plugin."
version: 0.0.5
repository: https://github.com/Wayaer/harmony_flutter_packages/tree/main/device_info_plus_harmonyos

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: '>=11.0.0 <14.0.0'
  device_info_plus_platform_interface: '>=7.0.0 <=8.0.0'

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: device_info_plus
    platforms:
      ohos:
        pluginClass: DeviceInfoPlusPlugin
